[site]
# The title of the site
title = "MattMusc Pictures"
# The name of the author
author = "Matteo Muscella"

# Site navigation links
# You can remove any navigation links or add more link by adding following lines
#     [[site.nav]]
#     icon = ""
#     link = ""
# Navigation links are added in the order encountered.

[[site.nav]]
icon = "assets/icons/home.svg"
link = "https://www.photos.mattmusc.com"

[[site.nav]]
icon = "assets/icons/instagram.svg"
link = "https://instagram.com/mattmusc"

# Setttings for photo size
[image]
# Width for thumbnail images
thumbnailWidth = 640
# Width for enlarged images
originalWidth = 2048
# Compress Quality (0~100), higher is better.
compressQuality = 100

# Layout for grids
[layout]
minColumn = 1
maxColumn = 4
minWidth = 200

# Photo sections
# You can remove or add more sections by adding following lines
#     [[section]]
#     title = "section title"
#     text = "section description"
#     slug = "section-slug"
#     folder = "folder of photos"
#     ascending = false
# Photo sections are added in the order encountered.
[[section]]
title = ""
text = "I'm just a guy with some cameras and some lenses :)"
slug = "portfolio"
folder = "/Users/mattmusc/Pictures/Exports/Portfolio"
ascending = false

# Other setings
[others]
# Folders that should be copied together when exporting sites
folders = [ "assets", "media" ]
# Show `Generated by foto` footer or not
show_foto_footer = true
